### ISSUE TITLE
AMC-BLDC - finalize the test support with the official test jig

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#38]
## Task description
Following #34, we need to finalize the test support with the official test jig

## Definition of Done
- [x]  Add PWM output test to [test FW](emBODY/eBcode/arch-arm/board/amcbldc/test)
- [x] Test the whole testplan using IPTS 
- [x] A new release of IPTS has been produced

cc @valegagge @marcoaccame @maggia80

**Comment by davidetome** [comment]
This morning I spoke w/ @maurizbo and he forecasted the jig available not before the 15th of March

cc @valegagge

**Comment by davidetome** [comment]
/remind me on the 15th of March

**Comment by fgarini** [comment]
Jig wired and ready to be used! see https://github.com/icub-tech-iit/ipts/issues/24#issuecomment-2245263310

**Comment by fgarini** [comment]
I will add in this issue a description of the features of the JIG for the AMC-BLDC together with a description of the tests with the limit requirements for the pass/fail.
cc @MSECode

**Comment by MSECode** [comment]
Regarding the test of the PWM for the amc-bldc test procedure we were able to add this test and we have checked that we are actually activating the PWM phases as shown by the image below where a current is shown on the oscilloscope:

![Image](https://github.com/user-attachments/assets/a75bdeb6-a7ba-48b6-bfea-2c35e71b15e9)

For now we just send 50% of the max pwm on all the 3 phases.

In order to finalize the test we need to add the check of the currents on the adc.

**Comment by MSECode** [comment]
Release created: https://github.com/icub-tech-iit/ipts/releases/tag/v1.5.2

Closing sice DoD satisfied.
