### ISSUE TITLE
New release for IPTS, to test boards MTB4 (12008.C) and STRAIN2(11996.C)

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/ipts#5]
## Task Description
According to this [comment](https://github.com/icub-tech-iit/purchases/issues/1594#issuecomment-1090262414) and as discussed with @davidetome and @pattacini, it's necessary to change the test firmware for the new boards:
- Cod.12008.C - MTB4, IIT - Electronic board for tactile sensor, with 3 axis accelerometers Vin 5Vcc
- Cod.11996.C - STRAIN2, IIT - Electronic board, 6 channels strain gauges variable gain interface board with CAN/UART, Temperature sensor, IMU, STM32L4

## Definition of Done
New release for IPTS is ready and tested with the new boards MTB4 (cod.12008.C) and STRAIN2 (cod.11996.C).

**Comment by davidetome** [comment]
Started w/ CubeMx prj, unfortunately is not possible to retarget the existing prj to the new uP even if it is fully compatible.

I picked up from @icub-tech-iit/proto : 

- MTB4 test equipment SN002
- ST-LINK debugger SN B201833
- DB9/molex CAN cable w/ USB PS (@gsisinna )

I'll bring all back once finished 👍🏻 

cc @pattacini @maggia80

**Comment by davidetome** [comment]
Just added the `CubeMx` prj for `mtb4` in my fork w/ this [commit ](https://github.com/davidetome/ipts/commit/29c4950aeb8f50b70902ab7eb4eeb25044b530d5)

**Comment by davidetome** [comment]
I tested a blinky led app for the `mtb4` and I noticed that all the boards have the blue led reversed (@MrAndrea  fixed it on 2 boards 🎖️ ), I'll add the tests then.

Now I'm going to test a blinky led app also on `starin2` in order to see I f also these boards at least are alive and programmable as requested by @maggia80.

cc @pattacini

**Comment by MrAndrea** [comment]
We have to contact the supplier to ask for the replacement of the blue led `DL1` with the right mounting.
Which is the order corresponding to this batch production? [this one](https://github.com/icub-tech-iit/purchases/issues/1594)?

**Comment by davidetome** [comment]
@MrAndrea I would wait also to check strain2 and adapt test firmware to the new 2tm32l452 uP since we may notice other issues
We already agree w/ them to come at CRIS once test firmware are ready to pick up  the boards

cc @pattacini @maggia80 @Fabrizio69

**Comment by davidetome** [comment]
I created the `CubeMX `prj also for `strain2`; I'm able to flash the board but, unfortunately, the LED doesn't blink.
Tomorrow morning I'll check if the LED is correctly soldered.

cc @maggia80 @pattacini @MrAndrea

**Comment by davidetome** [comment]
Hi @marcoaccame , as anticipated I'm facing some problems w/ the `mtb4` test FW.
I tried to compile the old prj w/ the same ST library used in `icub-firmware` but the `CAN` driver seems to be changed from the oldest library I used.
So I tried to compile the new prj w/ the same library I used but I got errors on `CAN` driver as well.

As agree, please let me know a time slot convenient for you on Monday so I can show you in particular

**Comment by davidetome** [comment]
I had a T2T w/ @marcoaccame and, as anticipated, the problem belongs to the old library used for the test FW and it is also not compatible w/ the new uP.

Apparently, it boils all down to the CAN driver change.

We tried to fix porting the library used to the one used by the official application but it seems to require a certain effort.

Seen that we thought it might be worth to port the test FW using the same library of the application and using the framework we use for our boards (not low-level HAL); this surely requires an effort but it could be a good exercise for me to better understand the FW environment, also for future needs..

Otherwise, we have to adapt the test FW using a newer library. 

cc @pattacini @maggia80

**Comment by pattacini** [comment]
>this surely requires an effort but it could be a good exercise for me to better understand the FW environment, also for future needs..

👍🏻

**Comment by davidetome** [comment]
This morning I had another T2T w/ @marcoaccame ; as anticipated we started having an overview of the basic apps for `pmc` (as an example) and `mtb4`.

We decided to start from the `bootloader` project of the mtb4 that contains the basic functionality we need  (a thread that waits and responds to the CAN bus) and add the functions that perform the tests from the old test firmware.

cc @pattacini @maggia80

**Comment by marcoaccame** [comment]
> We'll do this first on the `mtb4.B` as we know everything works; then we'll port the project w/ the new uP

So, the plan is this one.
- [ ] Create in `icub-firmware` a new `test` application for the `mtb4` (version B) which is a simplification of `bootloader`. The `test` application will just manage basic CAN communication using the `embot::hw::can` driver which we use in all our recent boards. The parsing of the CAN frame will be left out at first.
- [ ] Add the specific parsing of CAN frames used for testing plus the associated actions. This is what is already available in [here](https://github.com/icub-tech-iit/ipts/blob/master/ipts-test-firmware/mtb4/fw/Src/main.c) and used to perform the test.
- [ ] Make sure that the `test` application  works fine w/ the current setup on the `mtb4` version B.
- [ ] Build the `stm32hal` library for the new `mtb4c` board (version C) using cubemx as described in [here](https://github.com/robotology/icub-firmware/blob/master/emBODY/eBcode/arch-arm/libs/lowlevel/stm32hal/docs/stm32lib.howto.md) (with any version of HAL driver we want) and use it with the `test` application as described in following point.
- [ ] Copy and adapt the `test` application developed and tested for the `mtb4` board so that it can work with the  `stm32hal` library for the new `mtb4c` board.
- [ ] Use the new `test` application to validate the mtb version C boards

At this point we can surely test the new boards but we can also produce very quickly the `bootloader` and `application` and `updaterofbootloader` for the new `mtb4c` board. 

And for the new `strain2c` we shall only need to build the stm32hal library for the new micro.

**Comment by davidetome** [comment]
Thanks to the training I had w/ @marcoaccame , Today I managed to test the `CAN` communication for the  `mtb4.B` test application.
I then inserted the first basic 3 tests : 

- Chech test Firmware version
- Test LEDs OFF
- Test LEDs ON

As we can see, sending the corresponding command the `mtb4` reacts accordingly : 


https://user-images.githubusercontent.com/6638215/170695952-6acce9c2-d6c7-476e-b004-a7cdfd2f4f7b.mp4



Next sprint I will go on adding the other tests and better formatting the code.

**Comment by pattacini** [comment]
Nice!

**Comment by davidetome** [comment]
Today I managed to add the remaining tests for the `mtb4.B` w/ the `embot` framework.
Everything works but a GPIO that I need to make as output; on Monday I'll ask @marcoaccame..

[0002_12008.B.txt](https://github.com/icub-tech-iit/ipts/files/8834066/0002_12008.B.txt)

Then we can move to the new `lib` for the new `uP`.

cc @pattacini @maggia80

**Comment by davidetome** [comment]
This morning I had a T2T w/ @marcoaccame and we solved the `GPIO ` config problem.
So the `mtb4.B` test FW w/ the `embot ` framework is fully working.

This afternoon we had another meeting where @marcoaccame showed me how to produce the new  `stm32hal ` lib for the new micro.
We also produced a basic demo project (blinking led) and I tested it successfully.

Next steps are : 
- verify some params in the CubeMx  project
- modify the mtb4.B test project w/ the new lib for the` mtb4.C `.
- verify everything works

cc @pattacini @maggia80

**Comment by davidetome** [comment]
## The `mtb4.C` test `FW `is ready.

Today I tested the new firmware w/ the `IPTS `suite. 
Since I review also the FW for the `mtb4.B` using the `embot `framework I tested it too.
Everythink works:

[0000_12008.B.txt](https://github.com/icub-tech-iit/ipts/files/8908203/0000_12008.B.txt)
[0000_12008.C.txt](https://github.com/icub-tech-iit/ipts/files/8908204/0000_12008.C.txt)

⚠️ For the C revision the final programming of `bootloader `and `application `is not possible since I have to modify them w/ the new library for the new uP; finally we need also to make some changes to the high-level code in order to make the` mtb4C 
` board usable

cc @pattacini @marcoaccame @maggia80 @Fabrizio69 @emilianob80

**Comment by Fabrizio69** [comment]
Hi @davidetome , from the [previous comment](https://github.com/icub-tech-iit/ipts/issues/5#issuecomment-1156268474) I understand that we can't send to the provider, the  boards tor the test (see [purcase issue](https://github.com/icub-tech-iit/purchases/issues/1594). Is it correct?

**Comment by davidetome** [comment]
ciao @Fabrizio69, 

 yesterday I managed to produce the new `bootloader` and I'm going to do the same for the `application`; anyway, we need to test them accurately before merging. So what I propose to do is to make the first release of `IPTS` containing local binaries (at least bootloader), in this way the boards will be discoverable and updatable.

Once the binaries are merged, we can make a new release letting `IPTS` pull the binaries from the repo as usual.

Sounds good to you?

cc @pattacini @marcoaccame @maggia80

**Comment by davidetome** [comment]
Added mtb4c `bootloader` and `application` in my `icub-firmware` [fork](https://github.com/davidetome/icub-firmware/tree/mtb4-test).
The board is correctly discoverable : 

![btl](https://user-images.githubusercontent.com/6638215/174056261-0c21a000-090f-49be-a4fe-0373a8b6c952.png)
![app](https://user-images.githubusercontent.com/6638215/174056258-a7319cc6-4639-440f-b5fb-c118223a6767.png)

The board is still `unknown` due to the fact I have to compile `icub-main` w/ the mods pushed in my [icub-firmware-shared ](https://github.com/davidetome/icub-firmware-shared/commit/aff334eafc51b13eba2e53a822d1b9f8a1188e7e )fork.

The next steps are : 

- Compile the mods and check that `FirmwareUpdater` correctly recognizes the `mtb4c`
- Do some tests w/ the new applications (skin service, IMU service, temperature service)

cc @marcoaccame @pattacini @maggia80 @MrAndrea @Fabrizio69

**Comment by Fabrizio69** [comment]
Hi @davidetome tell us when a new release for the IPTS is ready for the supplier.

**Comment by davidetome** [comment]
@Fabrizio69, I can make the release by today, and give you back the 10 `mtb4c` boards on Wednesday morning.
Let me know if it is ok for you!

**Comment by Fabrizio69** [comment]
Hi @davidetome it's OK for me, thanks

**Comment by davidetome** [comment]
New [release](https://github.com/icub-tech-iit/ipts/releases/tag/v1.1.0) of IPTS is available.
The link have be provided to the supplier.

cc @pattacini @Fabrizio69 @Andreamenini68

**Comment by davidetome** [comment]
Regarding the `bootloader` and `application` adaption, in particular about : 

> - Compile the mods and check that FirmwareUpdater correctly recognizes the mtb4c

I managed to compile my forked [icub-firmware-shared](https://github.com/davidetome/icub-firmware-shared) and the `FirmwareUpdater` correctly recognizes the new board `mtb4c`

![image](https://user-images.githubusercontent.com/6638215/174790268-4ee8a977-44e8-4404-a472-942ff2d4660b.png)
![image](https://user-images.githubusercontent.com/6638215/174789945-33cf33e4-2db6-4387-851e-8dc56ac93c46.png)

Now I've to check the functionality (i.e. skin, IMU, temperature)

**Comment by Miche19** [comment]
> @Fabrizio69 , I'm going to give @Miche19 the 10 `mtb4c` boards provided. The two ones marked with a white dot are tested and working.
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/6638215/174986400-12b3d8aa-864d-436d-b6c7-9740ba18f484.png">
> 
> cc @maggia80 @MrAndrea @Andreamenini68

ricevute da @davidetome

**Comment by davidetome** [comment]
@Fabrizio69 I think it would be worth keeping one `mtb4c` in order to test the new `bootloader` and `application`.
It's ok with you?

cc @pattacini @marcoaccame @maggia80 @Andreamenini68

**Comment by davidetome** [comment]
Closing this in favour of #9
