### ISSUE TITLE
New release for IPTS, to test boards STRAIN2C (11996.C)

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#9]
## Task Description
Following #5, it's necessary to change the test firmware for:

- Cod.11996.C - STRAIN2, IIT - Electronic board, 6 channels strain gauges variable gain interface board with CAN/UART, Temperature sensor, IMU, STM32L4

## Definition of Done

- [x] Release the test FW for `strain2 rev.B `using the `embot` framework
- [x] Produce the new library `stmhal` for the new `stm32l452X` uP
- [x] Release the test FW for `strain2 rev.C `using the `embot` framework
- [x] Add  `strain2c` test support in `IPTS` and produce a new release

cc @pattacini @marcoaccame @Fabrizio69 @maggia80 @MrAndrea @emilianob80

**Comment by davidetome** [comment]
Today I finally completed the `strain2 rev.B` test [firmware](https://github.com/davidetome/icub-firmware/commit/59b42b78f344e81e9eea0932c5e4c6694eda235e) using the `embot` framework.


![image](https://user-images.githubusercontent.com/6638215/177364586-495d61e7-9098-4e34-95f4-8e308a6a3377.png)


Tomorrow I'll proceed to produce the new `stm32hal `lib for the new micro and go on w/ the test FW for the `strain2c`

cc @marcoaccame @pattacini @maggia80 @Fabrizio69

**Comment by davidetome** [comment]
Today I managed to : 

- [x] Produce the new library `stmhal` for the new `stm32l452X` uP
- [x] Release the test FW for `strain2 rev.C `using the `embot` framework

The `strain2c`test FW works apparently fine but I've got problems w/ `pga308` testing on all the 4 boards I have.
In part are probably board assembling problems (ADC reading stuck to 0).

Tomorrow I'll try to debug the better one 👀 

All the mods are committed on my [fork](https://github.com/davidetome/icub-firmware/commit/0d74d7e612d06d681b24f964f00faf9d23e94dc6).

cc @marcoaccame @pattacini @maggia80 @Fabrizio69 @MrAndrea

**Comment by davidetome** [comment]
## Update
Today I did some debug activities trying to repair the faults on the boards.
Even if I didm't get a board fylly working, the situation has improved:

Board| Previous status|  New status| Notes |
------ | ------|------ |------|
1      |  LED KO, CAN KO     |  LED KO, CAN KO | Checked U8, U9 and related passive components w/o results |
2      |   BNO055 KO, STRAIN2 KO    |    STRAIN2 KO | Reviewed U10 soldering (IMU OK), Checked resistors presence/values but STRAIN2 ADC reading is stuck to 0 |
3      |   BNO055 KO, ALL STRAIN KO    |    BNO055 KO,   STRAIN6 KO | the IMU chip is flipped, reversing it will fix; reviewed soldering of some pga308 fixed 5 channels but STRAIN6 is saturated (8K) |
4      |   LED KO,  ALL STRAIN KO BUT STRAIN4   |   LED KO. STRAIN2, STRAIN6 KO |  reviewed soldering of some pga308 |

I should concentrate on BOARD 3 which seems to me to be the easiest one to fix, so tomorrow I'll try to understand why  STRAIN6 is saturated.
I'll need help from more expertized in soldering components to flip the IMU on board 3.


cc @maggia80 @marcoaccame @pattacini @Fabrizio69

**Comment by davidetome** [comment]
Today @maggia80 noticed to me that 16 `strain2c`were in the warehouse.

So I tested all of them, also taking the opportunity to fine-tune the` FW/SW`.

At this time I got 4 boards passing all the tests.

I think tomorrow morning we can get others, some boards in fact fail the `pga308 `test due to a small tolerance gap.

I'll speak w/ @marcoaccame to understand if we can enlarge the tolerance.
 I can also refine the test in the `FW `repeating the test for the failing channels by changing the `pga308 ` config.

Anyway, tomorrow I'll better document after final changes.
`
cc @maggia80 @pattacini @marcoaccame

**Comment by davidetome** [comment]
Today I [added ](https://github.com/davidetome/icub-firmware/commit/6dcc2fc85dc5434444cacc652a37a600af63404f#diff-bb72272fd218b40a8d20c59e2938de13cad3d9e7cfe64839b976188e53668ed1)the pga308 offstet regulation.

Tomorrow I'll test the boards and produce the `ipts `release.

cc @pattacini @maggia80 @marcoaccame @Fabrizio69

**Comment by davidetome** [comment]
With this [PR ](https://github.com/icub-tech-iit/ipts/pull/10)strain2c test support is available.

I tested all 20 boards  (6 pass and 14 fail).

[TestReports.zip](https://github.com/icub-tech-iit/ipts/files/9121673/TestReports.zip)


About the failing 14 boards:

- 5 boards have problem in CAN communication
- 9 boards have problems on analog channels (STRAIN1-6)

As soon as the PR is merged I'll produce the new `IPTS `release.

I bring the boards to @Miche19 , keeping the serial number 0 for next develpoments of bootloader/firmware.

**Comment by davidetome** [comment]
New IPTS [release ](https://github.com/icub-tech-iit/ipts/releases/tag/1.2.0)in online 👍🏻 

cc @pattacini @maggia80 @Fabrizio69
